[package]
name = "agency-proxy-client"
description = "Async client for the AgencyProxy local and remote wire protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
agency-proxy-protocol.workspace = true
endpoint-libs.workspace = true
futures.workspace = true
nagoya.workspace = true
serde_json.workspace = true
thiserror.workspace = true
